import '../styles/globals.css'
import SideBar from '@/components/SideBar/SideBar'
import SearchBar from '@/components/SearchBar/SearchBar';
import HeaderBtn from '@/components/HeaderBtn/HeaderBtn';


export const metadata = {
  title: 'Fluffy',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
      
        <main>

        </main>


        {children}</body>
    </html>
  )
}
