import '../styles/globals.css'
import SideBar from '@/components/SideBar/SideBar'
import SearchBar from '@/components/SearchBar/SearchBar';
import HeaderBtn from '@/components/HeaderBtn/HeaderBtn';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Flufly</title>
      </head>
      <body>
        <header>
        </header>
        <SideBar></SideBar>
        <main>
        <SearchBar />
        <HeaderBtn/>

        </main>
       

        {children}</body>
    </html>
  )
}
